dist: bionic
language: cpp

os:
  - linux

compiler:
  - clang
  - gcc

cache:
  directories:
    - $HOME/.cache

addons:
  apt:
    packages:
    - cmake
    - protobuf-compiler
    - qt5-default

jobs:
  include:
    - stage: compile
      script: echo compile
    - stage: test
      script: echo test

before_install:
  - sudo python -m pip install conan
  - mkdir build
  - conan install . -if build

install:
  - git clone https://github.com/Framstag/libosmscout
  - cd libosmscout
  - mkdir build
  - cd build
  - cmake .. || true
  - make Import
  - cd ../..

script:
  - cd build
  - cmake .. && make
  - cd ..

