language: cpp

os:
  - linux

compiler:
  - clang
  - gcc

cache:
  directories:
    - $HOME/.cache

addons:
  apt:
    packages:
    - cmake

before_install:
  - git clone https://github.com/Framstag/libosmscout
  - cd libosmscout
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ..
  - mkdir build
  - sudo apt-get update
  - sudo apt-get install -y qt5-default

install:
  - sudo python -m pip install conan

script:
  - conan install . -if build
  - cd build
  - cmake .. && make
  - cd ..

