dist: bionic
language: cpp

os:
  - linux

compiler:
  - clang
  - gcc

cache:
  directories:
    - $HOME/.cache

addons:
  apt:
    packages:
    - cmake
    - protobuf-compiler
    - libprotobuf-dev
    - qt5-default

jobs:
  include:
    - stage: test
      script: ./scripts/test.sh

install:
  - ./scripts/install.sh

script:
  - ./scripts/compile.sh
