dist: bionic
language: cpp

os:
  - linux

compiler:
  - clang
  - gcc

cache:
  directories:
    - $HOME/.cache

addons:
  apt:
    packages:
    - python3-pip
    - cmake

install:
  - ./scripts/install.sh

script:
  - ./scripts/compile.sh
  - ./scripts/test.sh
